# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Collab' do

pod 'Firebase', '>= 2.4.3'
pod 'FirebaseUI/Core', '~> 0.3'

end

target 'CollabTests' do

end

target 'CollabUITests' do

end

